name: Test Windows
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      balVersion:
        default: 2201.9.2
jobs:
  test_windows:
    name: Test action on Windows
    runs-on: windows-latest
    steps:
      - name: Set env
        run: |-
          echo "balVersion=$(
          if [[ -n "${{ github.event.inputs.balVersion }}" ]]; then
            echo ${{ github.event.inputs.balVersion }}
          else
            echo 2201.9.2
          fi
          )" >> $GITHUB_ENV
        shell: bash
      - uses: actions/checkout@v2
      - uses: ballerina-platform/setup-ballerina@main
        name: Test the action.
        with:
          version: ${{ env.balVersion }}
      - run: bal version
      - run: bal run hello.bal

  test_windows_nightly:
    name: Test action on Windows (nightly)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ballerina-platform/setup-ballerina@main
        name: Test the action.
        with:
          version: nightly-2201.9.x
      - run: bal version
      - run: bal run hello.bal
